apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: demo-db-creds
  namespace: default
spec:
  vaultAuthRef: demo-auth
  mount: database
  path: creds/demo-role
  destination:
    name: demo-db-secret
    create: true
  renewalPercent: 67
